const test=require('node:test'),assert=require('node:assert/strict');
const QueueMutationService=require('../services/queue-mutation-service');
const PlaybackController=require('../services/playback-controller');
const QuickAddUiController=require('../services/quick-add-ui-controller');
const OverlayEventService=require('../services/overlay-event-service');

test('queue mutation moves, pins and removes immutably',()=>{const s=new QueueMutationService(),q=[{id:1},{id:2},{id:3}];const moved=s.move(q,3,-1);assert.deepEqual(moved.queue.map(x=>x.id),[1,3,2]);const pinned=s.togglePin(q,2);assert.equal(pinned.item.isPinned,true);assert.deepEqual(s.remove(q,2).queue.map(x=>x.id),[1,3]);assert.deepEqual(q,[{id:1},{id:2},{id:3}]);});
test('queue mutation protects current and pinned positions',()=>{const s=new QueueMutationService();assert.equal(s.move([{id:1},{id:2}],2,-1,{hasCurrent:true}).changed,false);assert.equal(s.move([{id:1},{id:2,isPinned:true},{id:3}],3,-1).changed,false);});
test('playback controller normalizes controls',()=>{const calls=[],p=new PlaybackController({control:(...x)=>calls.push(x),update:()=>{}}),state={currentSong:{},isPlaying:false,volume:1};assert.equal(p.toggle(state).action,'play');assert.equal(p.seek(150,200),200);assert.equal(p.volume(state,-2),0);assert.deepEqual(calls,[['play'],['seek',200],['volume',0]]);});
test('overlay event service rejects duplicate and stale events',()=>{const s=new OverlayEventService({now:()=>5000}),state={lastHandledEndedEventId:'x',lastSwitchTime:0,currentSong:{id:1}};assert.equal(s.evaluate({type:'ended',eventId:'x'},state).reason,'duplicate');assert.equal(s.evaluate({type:'ended',songId:2},state).reason,'stale');assert.equal(s.evaluate({type:'ended',songId:1},state).action,'ended');});
test('overlay event service rejects player errors from an old song',()=>{const s=new OverlayEventService(),state={currentSong:{id:2}};assert.equal(s.evaluate({type:'player_error',songId:1,code:150},state).reason,'stale');assert.equal(s.evaluate({type:'player_error',songId:2,code:150},state).action,'player_error');});
test('overlay state progress respects start, end and max duration',()=>{const s=new OverlayEventService();const p=s.progress({duration:300,currentTime:70},{start:20,end:200},()=>100);assert.equal(p.limitDuration,100);assert.equal(p.elapsedTime,50);assert.equal(p.percent,50);});
test('overlay event service accepts the current song end without timing heuristics',()=>{const s=new OverlayEventService(),state={currentSong:{id:1,duration:2382}};assert.equal(s.evaluate({type:'ended',songId:1},state).action,'ended');});
test('overlay event service blocks ended before the new song starts',()=>{const s=new OverlayEventService(),state={currentSong:{id:2},currentSongPlaybackConfirmed:false};assert.equal(s.evaluate({type:'ended',songId:2,reason:'youtube_ended'},state).reason,'playback_not_confirmed');state.currentSongPlaybackConfirmed=true;assert.equal(s.evaluate({type:'ended',songId:2,reason:'youtube_ended'},state).action,'ended');});
test('overlay event service blocks legacy Vote Skip ended during transition',()=>{const s=new OverlayEventService({now:()=>5000}),state={currentSong:{id:2},currentSongPlaybackConfirmed:true,ignoreLegacyEndedUntil:10000};assert.equal(s.evaluate({type:'ended',songId:2},state).reason,'legacy_vote_skip_conflict');assert.equal(s.evaluate({type:'ended',songId:2,reason:'youtube_ended'},state).action,'ended');});
test('quick add UI reads defaults and clears form',()=>{const nodes={};for(const id of['donor-url','quick-donor-name','quick-donor-amount'])nodes[id]={value:id==='quick-donor-name'?'Mèo':''};nodes['quick-owner-add']={checked:true};nodes['quick-add-search-results']={style:{},innerHTML:'x'};nodes['quick-add-popover']={classList:{remove(v){this.value=v}}};const c=new QuickAddUiController({document:{getElementById:id=>nodes[id]}});assert.deepEqual(c.readOptions(),{donorName:'Mèo',amount:100000000,isOwnerAdd:true});c.clear();assert.equal(nodes['quick-add-search-results'].innerHTML,'');assert.equal(nodes['quick-add-popover'].classList.value,'visible');});
